issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - cyclop
    - path: heap/heap.go
      linters:
        - cyclop
    - path: sparse-table/rmq1.go
      linters:
        - cyclop
    - path: slices/slices_test.go
      linters:
        - paralleltest
        - govet
linters:
  enable:
    - paralleltest
    - gofumpt
    - gocritic
    - forbidigo
    - lll
    - whitespace
    - gofmt
    - godot
    - goimports
    - exhaustive
    - asciicheck
    - bidichk
    - cyclop
    - decorder
    - dogsled
    - dupl
    - exhaustruct
    - exportloopref
    - forcetypeassert
    - gochecknoglobals
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - predeclared
    - unconvert
    - gocognit
    - gocyclo
    - godox
    - grouper
    - importas
    - maintidx
    - makezero
    - misspell
    - unused
    - staticcheck
    - gosimple
    - govet
    - usestdlibvars
linters-settings:
  godot:
    scope: declarations
    period: true
  gocritic:
    disabled-checks:
      - unnamedResult
      - hugeParam
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated