issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - ifshort
        - cyclop
    - path: heap/heap.go
      linters:
        - cyclop
    - path: sparse-table/rmq1.go
      linters:
        - cyclop
linters:
  enable:
    - paralleltest
    - gofumpt
    - gocritic
    - forbidigo
    - lll
    - whitespace
    - gofmt
    - godot
    - goimports
    - exhaustive
    - asciicheck
    - bidichk
    - cyclop
    - decorder
    - dogsled
    - dupl
    - errname
    - errorlint
    - exhaustruct
    - exportloopref
    - forcetypeassert
    - gochecknoglobals
    - nakedret
    - nestif
    - nilnil
    - nolintlint
    - prealloc
    - predeclared
    - unconvert
    - wrapcheck
    - gocognit
    - goconst
    - gocyclo
    - godox
    - goerr113
    - goprintffuncname
    - grouper
    - importas
    - maintidx
    - makezero
    - misspell
    - unused
    - staticcheck
    - gosimple
  disable:
    - gci
    - revive
    - stylecheck
    - funlen
    - ifshort
    - structcheck


